version: "2"
linters:
  default: all
  disable:
    - wsl
    - gomodguard
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl_v5
    - gomodguard_v2
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - gocritic
        path: _test\.go
        text: Combine
      - linters:
          - gocritic
        path: _test\.go
        text: dupArg
        source: (assert|require).+Equal
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/oteldb/storage
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
