// Code generated by command: go run main.go -out minmax_amd64.s. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func minMaxInt64AVX2(s []int64) (rmin int64, rmax int64)
// Requires: AVX, AVX2, CMOV
TEXT ·minMaxInt64AVX2(SB), NOSPLIT, $64-40
	MOVQ         s_base+0(FP), AX
	MOVQ         s_len+8(FP), CX
	MOVQ         (AX), DX
	MOVQ         DX, BX
	XORQ         SI, SI
	VPBROADCASTQ (AX), Y0
	VMOVDQU      Y0, Y1
	MOVQ         CX, DI
	SUBQ         $0x03, DI

vecloop:
	CMPQ      SI, DI
	JGE       vecdone
	VMOVDQU   (AX)(SI*8), Y2
	VPCMPGTQ  Y2, Y0, Y3
	VPBLENDVB Y3, Y2, Y0, Y0
	VPCMPGTQ  Y1, Y2, Y3
	VPBLENDVB Y3, Y2, Y1, Y1
	ADDQ      $0x04, SI
	JMP       vecloop

vecdone:
	VMOVDQU Y0, (SP)
	VMOVDQU Y1, 32(SP)
	MOVQ    (SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    8(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    16(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    24(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    32(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    40(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    48(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    56(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX

tail:
	CMPQ    SI, CX
	JGE     done
	MOVQ    (AX)(SI*8), DI
	MOVQ    DX, R8
	CMPQ    DI, DX
	CMOVQLT DI, R8
	MOVQ    R8, DX
	MOVQ    BX, R8
	CMPQ    DI, BX
	CMOVQGT DI, R8
	MOVQ    R8, BX
	ADDQ    $0x01, SI
	JMP     tail

done:
	MOVQ DX, rmin+24(FP)
	MOVQ BX, rmax+32(FP)
	RET
