// Code generated by command: go run main.go -out minmax_amd64.s. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func minMaxInt64AVX2(s []int64) (rmin int64, rmax int64)
// Requires: AVX, AVX2, CMOV
TEXT ·minMaxInt64AVX2(SB), NOSPLIT, $64-40
	MOVQ         s_base+0(FP), AX
	MOVQ         s_len+8(FP), CX
	MOVQ         (AX), DX
	MOVQ         DX, BX
	XORQ         SI, SI
	VPBROADCASTQ (AX), Y0
	VMOVDQU      Y0, Y1
	MOVQ         CX, DI
	SUBQ         $0x03, DI

vecloop:
	CMPQ      SI, DI
	JGE       vecdone
	VMOVDQU   (AX)(SI*8), Y2
	VPCMPGTQ  Y2, Y0, Y3
	VPBLENDVB Y3, Y2, Y0, Y0
	VPCMPGTQ  Y1, Y2, Y3
	VPBLENDVB Y3, Y2, Y1, Y1
	ADDQ      $0x04, SI
	JMP       vecloop

vecdone:
	VMOVDQU Y0, (SP)
	VMOVDQU Y1, 32(SP)
	MOVQ    (SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    8(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    16(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    24(SP), DI
	CMPQ    DI, DX
	CMOVQLT DI, DX
	MOVQ    32(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    40(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    48(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX
	MOVQ    56(SP), DI
	CMPQ    DI, BX
	CMOVQGT DI, BX

tail:
	CMPQ    SI, CX
	JGE     done
	MOVQ    (AX)(SI*8), DI
	MOVQ    DX, R8
	CMPQ    DI, DX
	CMOVQLT DI, R8
	MOVQ    R8, DX
	MOVQ    BX, R8
	CMPQ    DI, BX
	CMOVQGT DI, R8
	MOVQ    R8, BX
	ADDQ    $0x01, SI
	JMP     tail

done:
	MOVQ DX, rmin+24(FP)
	MOVQ BX, rmax+32(FP)
	RET

// func minMaxFloat64AVX2(s []float64) (rmin float64, rmax float64)
// Requires: AVX, AVX2, SSE2
TEXT ·minMaxFloat64AVX2(SB), NOSPLIT, $64-40
	MOVQ         s_base+0(FP), AX
	MOVQ         s_len+8(FP), CX
	MOVQ         $0x7ff0000000000000, DX
	MOVQ         $0xfff0000000000000, BX
	MOVQ         DX, X0
	MOVQ         BX, X1
	VPBROADCASTQ X0, Y0
	VPBROADCASTQ X1, Y1
	VMOVDQU      Y0, Y2
	VMOVDQU      Y1, Y3
	XORQ         DX, DX
	MOVQ         CX, BX
	SUBQ         $0x03, BX

vecloop:
	CMPQ      DX, BX
	JGE       vecdone
	VMOVUPD   (AX)(DX*8), Y4
	VCMPPD    $0x03, Y4, Y4, Y5
	VBLENDVPD Y5, Y0, Y4, Y6
	VMINPD    Y6, Y2, Y2
	VBLENDVPD Y5, Y1, Y4, Y6
	VMAXPD    Y6, Y3, Y3
	ADDQ      $0x04, DX
	JMP       vecloop

vecdone:
	VMOVDQU Y2, (SP)
	VMOVDQU Y3, 32(SP)
	VZEROUPPER
	MOVSD   (SP), X0
	MOVSD   32(SP), X1
	MOVSD   8(SP), X2
	MINSD   X2, X0
	MOVSD   40(SP), X2
	MAXSD   X2, X1
	MOVSD   16(SP), X2
	MINSD   X2, X0
	MOVSD   48(SP), X2
	MAXSD   X2, X1
	MOVSD   24(SP), X2
	MINSD   X2, X0
	MOVSD   56(SP), X2
	MAXSD   X2, X1

tail:
	CMPQ    DX, CX
	JGE     done
	MOVSD   (AX)(DX*8), X2
	UCOMISD X2, X2
	JP      tailnext
	MINSD   X2, X0
	MAXSD   X2, X1

tailnext:
	ADDQ $0x01, DX
	JMP  tail

done:
	MOVSD X0, rmin+24(FP)
	MOVSD X1, rmax+32(FP)
	RET

// func equalFixed16AVX2(blob []byte, needle []byte, dst []byte)
// Requires: AVX, AVX2
TEXT ·equalFixed16AVX2(SB), NOSPLIT, $0-72
	MOVQ           blob_base+0(FP), AX
	MOVQ           needle_base+24(FP), CX
	MOVQ           dst_base+48(FP), DX
	MOVQ           dst_len+56(FP), BX
	VBROADCASTI128 (CX), Y0
	XORQ           CX, CX
	XORQ           SI, SI
	MOVQ           BX, DI
	SUBQ           $0x07, DI

loop8:
	CMPQ      CX, DI
	JGE       tail2setup
	VMOVDQU   (AX)(SI*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, R8
	NOTL      R8
	TESTL     $0x0000ffff, R8
	SETEQ     (DX)(CX*1)
	TESTL     $0xffff0000, R8
	SETEQ     1(DX)(CX*1)
	VMOVDQU   32(AX)(SI*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, R8
	NOTL      R8
	TESTL     $0x0000ffff, R8
	SETEQ     2(DX)(CX*1)
	TESTL     $0xffff0000, R8
	SETEQ     3(DX)(CX*1)
	VMOVDQU   64(AX)(SI*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, R8
	NOTL      R8
	TESTL     $0x0000ffff, R8
	SETEQ     4(DX)(CX*1)
	TESTL     $0xffff0000, R8
	SETEQ     5(DX)(CX*1)
	VMOVDQU   96(AX)(SI*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, R8
	NOTL      R8
	TESTL     $0x0000ffff, R8
	SETEQ     6(DX)(CX*1)
	TESTL     $0xffff0000, R8
	SETEQ     7(DX)(CX*1)
	ADDQ      $0x08, CX
	ADDQ      $0x80, SI
	JMP       loop8

tail2setup:
	SUBQ $0x01, BX

loop2:
	CMPQ      CX, BX
	JGE       done
	VMOVDQU   (AX)(SI*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, DI
	NOTL      DI
	TESTL     $0x0000ffff, DI
	SETEQ     (DX)(CX*1)
	TESTL     $0xffff0000, DI
	SETEQ     1(DX)(CX*1)
	ADDQ      $0x02, CX
	ADDQ      $0x20, SI
	JMP       loop2

done:
	VZEROUPPER
	RET
